# Generated by Django 4.2.15 on 2024-08-31 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='mastimage',
        ),
    ]
