# Generated by Django 4.2.15 on 2024-08-20 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='mastimage',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/'),
        ),
    ]
