# Generated by Django 4.2.15 on 2024-08-20 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_mastimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='mastimage',
            field=models.ImageField(blank=True, null=True, upload_to='media/masthead_images/'),
        ),
    ]
