# Generated by Django 4.2.15 on 2024-08-18 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_testimonial_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='name',
            field=models.CharField(default='Anna', max_length=100, unique=True),
        ),
    ]
