# Generated by Django 4.2.15 on 2024-08-18 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_testimonial_testimonial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='testimonial',
            field=models.TextField(blank=True),
        ),
    ]
