# Generated by Django 4.2.15 on 2024-08-18 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_testimonial_testimonial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Published'), (2, 'Archived')], default=0),
        ),
    ]
