# Generated by Django 4.2.15 on 2024-08-18 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_testimonial_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='service',
            field=models.IntegerField(choices=[(0, 'One-shot Personal Reset'), (1, '3-month Life Coaching plan'), (2, 'Business Consultancy'), (3, 'Tailored Plan')], default=0),
        ),
    ]
