# Generated by Django 4.2.15 on 2024-08-22 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_collaboraterequest_inquire'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='age',
            field=models.IntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='extra_detail',
            field=models.CharField(default='Job Title Here', max_length=100),
        ),
        migrations.AddField(
            model_name='collaboraterequest',
            name='service',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.service'),
        ),
    ]
